apiVersion: v1
kind: ConfigMap
metadata:
  name: codemender-config
  namespace: default
data:
  config.yaml: |
    server:
      endpoint: "codemender.pa.googleapis.com:443"
    # project_paths:
    #   - "/path/to/project"
    scan:
      extensions:
        include: [".py", ".java", ".go", ".js", ".ts", ".c", ".cc", ".cpp", ".h", ".rb", ".php"]
        exclude: [".min.js", ".generated.go", ".pb.go"]
      max_file_size_kb: 500
      incremental: true
    output:
      format: table
    tools:
      confirm_commands: false
      confirm_writes: false
    vcs:
      type: "git"
